name: Deploy to Dokku Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
  
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'develop'
          git_remote_url: 'ssh://dokku@82.197.67.78:2202/hello-api'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}